workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    environment:
      ios_signing:
        distribution_type: development
        bundle_identifier: "misamitma@icloud.com"
      vars:
        XCODE_PROJECT: "Xava.xcodeproj"
        XCODE_SCHEME: "Xava"
      xcode: latest
    scripts:
      - name: Build iOS app
        script: |
          xcode-project build-ipa \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - tazabievvv@gamil.com
